on:
    - push
    - workflow_dispatch
jobs:
    generate-files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: node ./scripts/json_to_md.js
            - uses: stefanzweifel/git-auto-commit-action@v4
