on: commit
jobs:
    generate-files:
        steps:
            - uses: actions/checkout@v3
            - run: node ./scripts/json_to_md.js
            - uses: stefanzweifel/git-auto-commit-action@v4
